import ChoiceDetail from './ChoiceDetail';
import LobbyIntro from './LobbyIntro';
import Results,{AchievementShelf} from './Results';
import {readProgress,persistRun,isCharacterUnlocked} from './achievements';
import {summarizeRun} from './outcomes';
import {runDebugMetrics} from './resultDebug';
import {drawStationPair,stationFor} from './stations';
import {StationMap} from './StationMaps';
import {Preparation,CharacterPreparation,StudentBag,StudentReport} from './StudentUI';
import {focusWindow} from './studentConfig';
import { lazy, Suspense, useEffect, useReducer, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, History, Clock3, Download, Footprints, Map, RotateCcw, Scissors, Ticket, TrainFront, Trophy, Volume2, VolumeX, X, Zap, CreditCard, GlassWater, ArrowUp, Navigation, CircleCheck, Backpack } from 'lucide-react';
import IdentitySearch from './IdentitySearch';
import CartoonScene from './CartoonScene';
import MetroJourney from './MetroJourney';
import HoldAction from './HoldAction';
import {EscalatorArt,ElderArt} from './StationEventArt';
import { LittleYou, TinyTrain, StationFloorMap } from './Scenes';
import { createStationRun,createCharacterStationRun, reducer, formatTime, clockTime, projectedTime, STOP_BEFORE, readRecords, saveRecord, type Run, type Action } from './engine';
import type { Choice } from './data';
const Station=lazy(()=>import('./Station'));
type Dialog='achievements'|'ticket'|'help'|'map'|'records'|null;
function Sheet({title,close,children,event=false}:{title:string;close?:()=>void;children:React.ReactNode;event?:boolean}){
 const ref=useRef<HTMLElement>(null);const closeRef=useRef(close);closeRef.current=close;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current?.();if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('button,[tabindex="0"]');if(!items?.length){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===items[0]||document.activeElement===ref.current)){e.preventDefault();items[items.length-1].focus();}else if(!e.shiftKey&&document.activeElement===items[items.length-1]){e.preventDefault();items[0].focus();}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);previous?.focus();};},[]);
 return <div className={'sheet-scrim '+(event?'event-scrim':'')}><section className="bottom-sheet" ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><span className="sheet-handle"/><header><h2>{title}</h2>{close&&<button className="round-icon" aria-label="关闭" onClick={close}><X size={21}/></button>}</header>{children}</section></div>;
}
function PaperTicket({run,compact=false}:{run:Run;compact?:boolean}){
 return <div className={'paper-ticket '+(compact?'compact':'')}><span className="ticket-punch"/><div className="ticket-paper-main"><div className="ticket-first"><b>{run.city.train}</b><span>今天出发 · 别拿错了</span><TrainFront size={24}/></div><div className="ticket-route"><strong>{run.city.stationName}</strong><ArrowRight size={20}/><strong>{run.city.destination}</strong></div><div className="ticket-detail"><span>发车 <b>{clockTime(run.departure)}</b></span><span>检票口 <b>{run.gate}</b></span><span>08车 · 06F</span></div></div><div className="ticket-paper-stub"><span>停止检票</span><strong>{clockTime(run.departure-STOP_BEFORE)}</strong><div className="ticket-barcode"/><small>一会儿见，别迟到</small></div><span className="ticket-stamp">就这趟！</span></div>;
}
function EventFrame({run,children}:{run:Run;children:React.ReactNode}){
 return run.phase==='station'?<section className="station-challenge" role="region" aria-label={run.event!.title}><header><h2>{run.event!.title}</h2></header>{children}</section>:<Sheet title={run.event!.title} event>{children}</Sheet>;
}
function EventSheet({run,dispatch}:{run:Run;dispatch:React.Dispatch<Action>}){
 const e=run.event!;const [taps,setTaps]=useState(0);const [wrong,setWrong]=useState('');const [dy,setDy]=useState(0);const start=useRef<number|null>(null);const done=useRef(false);const inter=e.interaction;const seconds=Math.max(0,Math.ceil((inter?.kind==='identity'?(run.identityStage==='wallet'?8:6):inter?.seconds??10)*(run.student?focusWindow(run.student.stats.focus):run.characterTime?.characterId==='worker'?focusWindow(run.characterTime.focus):run.characterTime?.characterId==='tourist'?(0.7+run.characterTime.focus/100*.6):1)-run.eventElapsed));
 const choose=(c:Choice)=>{if(done.current)return;done.current=true;dispatch({type:'CHOICE',choice:c});};
 const tap=()=>{const next=taps+1;setTaps(next);if(next>=(inter?.required??5))choose(e.choices[0]);};
 return <EventFrame run={run}><div className="event-timer"><span>{run.phase==='station'?'道路封锁 · 完成操作才放行':'啊哦，来不及慢慢想了'}</span><b key={seconds}>{run.eventOverdue?'仍需处理':seconds+'s'}</b></div><p className="event-copy">{inter?.kind==='identity'&&run.student?'检票要刷身份证。打开书包，按住翻找对应夹层。':e.description}</p>{e.id==='security-queue'&&run.student&&!run.student.observed&&<HoldAction seconds={2.5/focusWindow(run.student.stats.focus)} label="按住观察队伍" onComplete={()=>dispatch({type:'OBSERVE'})}/> }
 {inter?.kind==='hold'?<HoldAction seconds={(inter.required??2)*(run.student?.tea?1.25:1)} label={e.choices[0].label} onComplete={()=>choose(e.choices[0])}/>:inter?.kind==='identity'?(run.student?<StudentBag run={run} dispatch={dispatch}/>:<IdentitySearch run={run} dispatch={dispatch}/>):inter?.kind==='tap'?<div className="tap-challenge"><div className="tap-character" style={{transform:'translateX('+Math.min(taps*12,72)+'px)'}}><LittleYou characterId={run.character.id} motion={taps?'sprinting':'waiting'}/></div><div className="tap-dots">{Array.from({length:inter.required??5},(_,i)=><i key={i} className={i<taps?'done':''}>{i<taps?<Check size={15}/>:null}</i>)}</div><button className="big-action" onClick={tap}><Footprints size={23}/> {e.id==='escalator-operation'?'快走一步！':e.id==='board-train'?'冲上车！':'跑！跑！跑！'} <small>{taps}/{inter.required??5}</small></button></div>
 :inter?.kind==='swipe'?<div className="swipe-challenge"><div className={"swipe-bag "+(e.id==='bag-snag'?'snagged-backpack':'')} role="button" tabIndex={0} aria-label={e.id==='bag-snag'?'向上滑动解开背包肩带':e.id==='elder-detour-action'?'向上滑动侧身通过':'向上滑动提起箱子'} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose(e.choices[0]);}}} style={{transform:'translateY('+dy+'px)'}} onPointerDown={ev=>{start.current=ev.clientY;ev.currentTarget.setPointerCapture(ev.pointerId);}} onPointerMove={ev=>{if(start.current!==null){const d=Math.max(-90,Math.min(0,ev.clientY-start.current));setDy(d);if(d<-(run.student?Math.max(45,80-run.student.stats.agility*.2):65)){start.current=null;choose(e.choices[0]);}}}} onPointerUp={()=>{start.current=null;setDy(0);}} onPointerCancel={()=>{start.current=null;setDy(0);}}><ArrowUp size={26}/><span>{e.id==='bag-snag'?<Backpack size={70}/>:e.id==='elder-detour-action'?<LittleYou characterId={run.character.id}/>:'🧳'}</span><small>{e.id==='bag-snag'?'往上滑，解开肩带！':e.id==='elder-detour-action'?'向上滑，侧身绕开':'往上拉！'}</small></div>{run.phase!=='station'&&<button className="soft-action" onClick={()=>choose(e.choices[0])}>提起来 <ArrowUp size={18}/></button>}<p className="micro-hint">向上滑动图案 · 键盘可聚焦后按 Enter</p></div>
 :inter?.kind==='scan'?<div className="scan-challenge"><div className="scan-items">{[{id:'bottle',label:'水杯',icon:GlassWater},{id:'scissors',label:'剪刀',icon:Scissors},{id:'id',label:'身份证',icon:CreditCard}].map(({id,label,icon:Icon})=><button key={id} onClick={()=>id==='scissors'?choose(e.choices[0]):setWrong('不是这个。安检员说的是剪刀！')}><Icon size={32}/><span>{label}</span></button>)}</div><p className="micro-hint" role="status">{wrong||'点出需要交给安检员的物品'}</p></div>
 :inter?.kind==='escalators'?<div className="escalator-choices">{e.choices.map(c=><button key={c.label} onClick={()=>choose(c)}><b>{c.label}</b><EscalatorArt/><small>情况未知</small><span>选这一部 <ArrowRight size={14}/></span></button>)}</div>
 :inter?.kind==='gate-number'?<div className="gate-number-grid">{e.choices.map(c=><button key={c.label} onClick={()=>{dispatch({type:'CHOICE',choice:c});setWrong(c.label===run.gate?'':'看错了，重新核对车票 '+run.gate);}}>{c.label}</button>)}<p role="status">{wrong||'核对车票，再点检票口'}</p></div>:inter?.kind==='gates'?<div className="eight-gates">{e.choices.map((c,i)=><button key={c.label} onClick={()=>choose(c)}><b>{c.label}</b><div className="queue-people">{Array.from({length:Math.max(1,Math.round(c.seconds/10))},(_,j)=><i key={j}/>)}</div><span>{c.detail.split(' · ')[0]}</span><small>{c.detail.split(' · ')[1]}</small></button>)}</div>
 :<>{(e.id==='elder-block'||e.id==='elder-outcome')&&<ElderArt grandma={run.stationLuck.elder==='grandma'} scam={e.id==='elder-outcome'&&run.stationLuck.elderScam}/>} {inter?.kind==='escalator-ride'&&<div className="escalator-reveal"><EscalatorArt state={run.stationLuck.escalators[run.escalatorLane!]}/></div>}<div className="event-buttons">{e.choices.map((c,i)=><button key={c.label} className={i===0?'big-action':'soft-action'} onClick={()=>choose(c)}><span><strong>{c.label}</strong><ChoiceDetail text={c.detail}/></span><ArrowRight size={22}/></button>)}</div></>}
 <p className="sheet-fine">{run.student||run.phase==='station'?'处理完才能继续 · 读题和操作按正常速度计时。':'来不及操作会多花时间，旅程会继续。'}</p></EventFrame>;

}
function EventLayer({run,dispatch}:{run:Run;dispatch:React.Dispatch<Action>}){
 const [held,setHeld]=useState<Run|null>(null);
 useEffect(()=>{
  if(run.event){setHeld(run);return;}
  const timer=setTimeout(()=>setHeld(null),200);return()=>clearTimeout(timer);
 },[run.event?.id,run.id]);
 const view=run.event?run:held;
 if(!view?.event)return null;
 return <div className={!run.event?'event-leaving':''} aria-hidden={!run.event}><EventSheet key={view.id+view.event.id} run={view} dispatch={dispatch}/></div>;
}
export default function App(){
 const [progress,setProgress]=useState(readProgress);const [progressSaved,setProgressSaved]=useState(true);
 const [stationOptions,setStationOptions]=useState(()=>drawStationPair());
 const [run,dispatch]=useReducer(reducer,undefined,()=>createStationRun(stationOptions[0].id));const [dialog,setDialog]=useState<Dialog>(null);const [sound,setSound]=useState(false);const [feedback,setFeedback]=useState<{key:number;text:string;loss:boolean}|null>(null);const [records,setRecords]=useState(readRecords);const [swapped,setSwapped]=useState(()=>Math.random()>.5);const [notice,setNotice]=useState('');const [pressed,setPressed]=useState(false);
 const debuggedRun=useRef<string|null>(null);const audio=useRef<AudioContext|null>(null);const lastBeep=useRef(0);const minute=useRef(-1);const logCount=useRef(0);const phaseRef=useRef(run.phase);const hud=useRef<HTMLDivElement>(null);
 const active=run.phase!=='lobby'&&run.phase!=='result';const before=['lobby','route','direction','wrong','metro','arrival','transfer','metro-recovery'].includes(run.phase);const time=run.student?(run.gatePassed?run.remaining:run.remaining-STOP_BEFORE):before?projectedTime(run):run.gatePassed?run.remaining:run.remaining-STOP_BEFORE;const urgency=time<=60?'critical':time<=180?'hurry':time<600?'warm':'calm';const seconds=Math.max(0,Math.ceil(time));
 useEffect(()=>{let last=Date.now();const id=setInterval(()=>{const now=Date.now();dispatch({type:'TICK',dt:(now-last)/1000});last=now;},100);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(run.logs.length>logCount.current){const l=run.logs.at(-1)!;setFeedback({key:Date.now(),text:l.seconds?'−'+l.seconds+'秒':'漂亮！没耽误',loss:l.seconds>0});}logCount.current=run.logs.length;},[run.logs.length]);
 useEffect(()=>{if(!feedback)return;const id=setTimeout(()=>setFeedback(null),1800);return()=>clearTimeout(id);},[feedback]);
 useEffect(()=>{if(run.phase==='result'){if(import.meta.env.DEV&&debuggedRun.current!==run.id){debuggedRun.current=run.id;console.debug('[train-rush:result]',runDebugMetrics(run,summarizeRun(run)));}saveRecord(run);setRecords(readRecords());const awards=persistRun(run,progress);setProgress(awards.progress);setProgressSaved(awards.saved);setDialog(null);window.scrollTo({top:0});}},[run.phase,run.id]);
 useEffect(()=>{if(phaseRef.current!==run.phase){if(run.phase==='route'||run.phase==='station')window.scrollTo({top:0,behavior:'smooth'});phaseRef.current=run.phase;}},[run.phase]);
 useEffect(()=>{const m=Math.floor(time/60);if(active&&time<180&&minute.current!==m){minute.current=m;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)hud.current?.animate([{transform:'translateY(0)'},{transform:'translateY(-4px)'},{transform:'translateY(0)'}],{duration:350});if(!matchMedia('(prefers-reduced-motion: reduce)').matches)navigator.vibrate?.(20);}if(!sound||!active||time>60||Date.now()-lastBeep.current<900)return;lastBeep.current=Date.now();try{const ctx=audio.current;if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=time<20?780:580;gain.gain.setValueAtTime(.018,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.1);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.11);}catch{}},[seconds,sound,active]);
 const reset=()=>{const next=drawStationPair();setStationOptions(next);setSwapped(Math.random()>.5);dispatch({type:'NEW',run:createCharacterStationRun(next[0].id,run.character.id as 'student'|'worker'|'tourist',run.hard)});setDialog(null);setFeedback(null);setPressed(false);minute.current=-1;logCount.current=0;};
 const toggleSound=()=>{if(!sound){try{audio.current??=new AudioContext();void audio.current.resume();}catch{return;}}setSound(!sound);};
 const saveImage=()=>{const outcome=summarizeRun(run);const canvas=document.createElement('canvas');canvas.width=750;canvas.height=980;const c=canvas.getContext('2d')!;c.fillStyle='#fbf5e8';c.fillRect(0,0,750,980);c.fillStyle='#615241';c.font='bold 35px sans-serif';c.fillText('我一定会赶上这趟车！',70,100);c.font='22px sans-serif';c.fillStyle='#ae9678';c.fillText(run.city.stationName+' · '+run.city.train+' · '+run.character.name,70,160);c.fillStyle=run.success?'#879b6c':'#c88762';c.font='bold 38px sans-serif';c.fillText(outcome.title,70,300);c.font='bold 88px monospace';c.fillText(run.success?formatTime(run.gateRemaining):outcome.distanceToTarget===null?'地铁途中':outcome.distanceToTarget+'m',70,435);c.font='22px sans-serif';c.fillText(run.success?'检票时距离停止检票':'距离'+(run.gatePassed?'车门':'检票口')+'（约）',70,486);c.fillStyle='#9f886b';c.fillText(run.success?'赶上的关键：':'这一局的关键原因：',70,585);const line=outcome.reasons[0]??outcome.summary;c.font='22px sans-serif';c.fillText(line.slice(0,27),70,640);if(line.length>27)c.fillText(line.slice(27,54),70,675);c.font='21px sans-serif';c.fillStyle='#587d6c';c.fillText(outcome.tags.map(t=>'#'+t).join('  '),70,780);c.font='19px sans-serif';c.fillText('小小的人，赶大大的车。',70,922);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='这趟车我赶上了吗.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('战绩图片已保存');setTimeout(()=>setNotice(''),2500);});};
 return <div className={'game-app station-theme-'+run.city.id+' phase-'+run.phase+' '+(active?'playing':'')+' '+urgency} style={{'--station-accent':stationFor(run).accent,'--station-paper':stationFor(run).paper} as React.CSSProperties}>
 <header className="game-header"><button className="game-wordmark" onClick={()=>setDialog('help')}><span className="logo-train"><TrainFront size={22}/></span><span>这趟车，<b>我赶定了</b></span></button><div className="header-tools">{!active&&<button className="round-icon" aria-label="成就册" onClick={()=>setDialog('achievements')}><Trophy size={19}/></button>}{!active&&<button className="round-icon" aria-label="赶车记录" onClick={()=>setDialog('records')}><History size={19}/></button>}<button className="round-icon" aria-label={sound?'关闭音效':'开启音效'} onClick={toggleSound}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="round-icon" aria-label="游戏玩法" onClick={()=>setDialog('help')}><CircleHelp size={19}/></button>{active&&<button className="pocket-ticket" aria-label="打开车票" onClick={()=>setDialog('ticket')}><Ticket size={24}/><span>{run.city.train}</span></button>}</div></header>
 <main className="play-area">
 {run.phase==='lobby'?<section className="opening"><LobbyIntro run={run} progress={progress} onSelect={id=>{if(isCharacterUnlocked(progress,id))dispatch({type:'NEW',run:createCharacterStationRun(run.city.id,id,run.hard)});}}/><section className="station-picker" aria-label="从本轮随机的两座车站中选择">{stationOptions.map(st=><button className={run.city.id===st.id?'selected':''} key={st.id} aria-pressed={run.city.id===st.id} onClick={()=>dispatch({type:'NEW',run:createCharacterStationRun(st.id,run.character.id as 'student'|'worker'|'tourist',run.hard)})}><StationMap station={st} mini/><b>{st.name}</b><small>{st.short}</small></button>)}</section><div className="opening-world station-overview"><StationMap station={stationFor(run)}/><p>{stationFor(run).feeling}</p><div className="opening-time"><Clock3 size={18}/><div><span>距离停止检票</span><strong>{formatTime(run.remaining-STOP_BEFORE)}</strong><small>{stationFor(run).strategy}</small></div></div></div><div className="opening-bottom"><div className="opening-ticket"><PaperTicket run={run}/></div></div><div className="lobby-departure"><div className="departure-selection"><span>这趟去</span><b>{run.city.stationName}</b><small>{run.character.name} · {run.hard?'极限踩点':'普通模式'}</small></div><button className="big-action start-action" onClick={()=>{setPressed(true);dispatch({type:'START'});}}>现在出发 <ArrowRight size={20}/></button></div><div className="opening-options"><button className={run.hard?'hard-switch selected':'hard-switch'} onClick={()=>dispatch({type:'NEW',run:createCharacterStationRun(run.city.id,run.character.id as 'student'|'worker'|'tourist',!run.hard)})}><Zap size={15}/>{run.hard?'极限踩点已开启':'想刺激一点？极限踩点'}<span>{run.hard?'开':'关'}</span></button><span>六站随机抽两站，每轮自己选一站；大学生通关后解锁打工人。</span></div></section>
 :run.phase==='result'?<Results run={run} progress={progress} saved={progressSaved} replay={reset} share={saveImage} selectStation={reset}/>

 :<><div className="hud-wrap"><div className={'time-capsule '+urgency} ref={hud}><span className="hud-train">🚄</span><div><span>{before&&!run.student?'预计下地铁后还剩':run.gatePassed?'已经检票！距离发车':'距离停止检票'}</span><strong key={urgency==='critical'?seconds:'stable'}>{formatTime(time)}</strong></div>{feedback&&<span key={feedback.key} className={'time-pop '+(feedback.loss?'loss':'good')}>{feedback.text}</span>}</div><button className="map-bubble" aria-label="查看路线" onClick={()=>setDialog('map')}><Map size={21}/></button></div>
 <div className="scene-heading"><span>{run.phase==='preparation'?'这次，准备怎么出门？':run.phase==='route'?'先做个决定':run.phase==='direction'?'上车前，看清方向':run.phase==='wrong'?'糟糕，坐反了':run.phase==='station'?'下车才是开始':run.phase==='arrival'?'到站了，认清站名':run.phase==='transfer'?'换乘中':run.phase==='metro-recovery'?'别慌，还能挽回':'跟着你选的路线走'}</span><h2>{run.phase==='preparation'?'现在花时间，还是后面再说？':run.phase==='route'?'哪条路，能救我一命？':run.phase==='direction'?'这边，还是那边？':run.phase==='wrong'?'下一站，赶紧折返！':run.phase==='station'?'最后几分钟，跑起来。':run.phase==='arrival'?'这一站，下不下？':run.phase==='transfer'?'跑过通道，再上一班。':run.phase==='metro-recovery'?'多绕一段，继续赶车。':'在哪下车，由你决定。'}</h2></div>
 {run.phase==='preparation'&&(run.student?<Preparation run={run} dispatch={dispatch}/>:<CharacterPreparation run={run} dispatch={dispatch}/>)}
 {run.phase==='route'&&<section className="route-scene"><div className="platform-background"><div className="platform-sign"><span>M</span>{run.city.spawnStations[run.spawn].name} <ArrowRight size={18}/><b>{run.city.stationName}</b></div><div className="platform-little"><LittleYou characterId={run.character.id} motion="waiting"/><span>脑子快转，脚还不能停。</span></div></div><div className="route-options">{run.city.spawnStations[0].routes.map((r,i)=><button className="route-option" key={r.id} onClick={()=>dispatch({type:'ROUTE',route:r})}><span className="route-line-symbol" style={{background:r.color}}>{r.lines[0]}</span><span className="route-option-main"><strong>{r.lines.join(' → ')}号线{r.transfers?'换乘':'直达'}</strong><span>游戏估时 {r.minutes} 分钟 · {r.transfers?r.transfers+' 次换乘':'不换乘'} · 步行 {r.walk}m</span><small className={'route-personality route-'+i}>{r.transfers?r.via+'下车换 '+r.lines[1]+' 号线':'经过 '+r.stops[r.stops.length-2]+' · 火车站下车'}</small></span><span className="route-margin"><small>下车后约剩</small><b>{formatTime(projectedTime(run,r))}</b><ChevronRight size={21}/></span></button>)}</div><p className="scene-whisper">途中有 30% 概率遇到意外。到站后，自己决定下不下车。</p></section>}
 {run.phase==='direction'&&<section className="direction-scene"><div className="platform-sign"><span>M</span>{run.route!.lines[0]}号线 <b>{run.city.spawnStations[run.spawn].name}站</b></div><div className="platform-floor"><div className="platform-yellow"/><div className="direction-you"><LittleYou characterId={run.character.id} motion="waiting"/><span>抬头，先看站台指示牌。</span></div><div className="platform-bench"/></div><div className="direction-choices">{[swapped,!swapped].map((correct,i)=><button key={i} className="direction-choice" onClick={()=>dispatch({type:'DIRECTION',correct})}>{i?<ArrowRight size={32}/>:<ArrowLeft size={32}/>}<strong>{correct?run.route!.direction:run.route!.opposite}</strong><span>这边上车</span></button>)}</div><button className="quiet-button" onClick={()=>setDialog('map')}><Map size={16}/> 偷看一眼线路图，时间不停哦</button></section>}
 {run.phase==='wrong'&&<section className="wrong-scene"><TinyTrain/><div className="wrong-little"><LittleYou characterId={run.character.id} motion="panic"/></div><p>方向错了，车还是照样开。<br/>下一站下车，再跑去对面站台。</p><span>折返要多花 75 秒</span></section>}
 {['metro','arrival','transfer','metro-recovery'].includes(run.phase)&&<MetroJourney run={run} dispatch={dispatch}/>}
 {run.phase==='station'&&<Suspense fallback={<div className="loading-station"><LittleYou characterId={run.character.id} motion="running"/><span>冲出车门，车站就在前面…</span></div>}><Station run={run} dispatch={dispatch} blocked={!!run.event||!!dialog}>{run.event&&<EventSheet key={run.event.id} run={run} dispatch={dispatch}/>}</Station></Suspense>}
 <p className="play-footer">{run.phase==='station'?'左右换道躲障碍 · 冲刺可选 · 撞上换道继续':run.city.spawnStations[run.spawn].name+' → '+run.city.stationName}</p>
 </>}
 </main>
 {!active&&<footer className="game-footer"><span>可以狼狈，不可以迟到。</span><span>没有账号，没有广告，只有一趟快赶不上的车。</span></footer>}
 {pressed&&active&&<div className="ticket-flight" aria-hidden="true" onAnimationEnd={()=>setPressed(false)}><Ticket size={42}/></div>}
 {dialog&&!run.event&&<Sheet title={dialog==='ticket'?'车票在这儿，没丢。':dialog==='map'?'往哪走？看这一眼。':dialog==='records'?'这些年，你赶过的车':dialog==='achievements'?'我的赶车成就册':'别慌，玩法很简单。'} close={()=>setDialog(null)}>
 {dialog==='ticket'&&<><PaperTicket run={run}/><div className="sheet-player"><LittleYou characterId={run.character.id}/><span><b>背包大学生</b><small>背着书包赶车，小心肩带和拥挤的通道。</small></span></div><p className="sheet-note">发车前 3 分钟停止检票。现在 {clockTime(run.departure-run.remaining)}，别在这儿看太久。</p></>}
 {dialog==='help'&&<div className="help-steps"><p><b>先坐上地铁</b><span>选路线，认方向。沿途行驶合计约 7 秒，30% 的旅程会遇到一次意外。不同路线经过不同站点。</span></p><p><b>这一站，下不下？</b><span>每站开门 4 秒，可下车或继续坐。换乘路线要在约定站下车换线；下早了、错过换乘或坐过站，都会耽误时间。没操作就继续坐。</span></p><p><b>小人由你控制</b><span>点开始前进，小人自动向前；左右按钮或横滑换道，按住冲刺加速。撞上障碍会停住，换到空道继续。键盘 A/D 或左右键换道，空格冲刺，P 休息。</span></p><p><b>碰上麻烦，手要快</b><span>先选择，再操作：背包向上滑解开，老人选绕开再侧身通过；扶梯连点快走或按住等候。处理完才放行，超时不会自动跳过。</span></p><div className="sheet-note">赶路时游戏时间以 4 倍流逝，读题、操作和休息时按正常速度流逝。普通模式不需要持续冲刺也能通关。一局约 3–5 分钟。路线分钟为游戏估时，不用于真实出行。</div><button className="big-action" onClick={()=>setDialog(null)}>知道了，赶车去！<ArrowRight size={20}/></button></div>}
 {dialog==='map'&&run.phase==='station'&&<><div className="map-reminder"><Clock3 size={16}/>还剩 {formatTime(time)}，别看太久。</div><StationMap station={stationFor(run)} run={run}/><p className="map-strategy">{stationFor(run).strategy}</p><StationFloorMap run={run}/>{run.student&&!run.student.mapRead&&<HoldAction seconds={2.5/focusWindow(run.student.stats.focus)} label={'记住本站路线和 '+run.gate} onComplete={()=>dispatch({type:'READ_MAP'})}/>}{run.student?.mapRead&&<p>记住了：{run.gate}。{stationFor(run).strategy}</p>}<p className="sheet-fine">按顺序通过各段，障碍处理完才能前进。</p></>}
 {dialog==='map'&&run.phase!=='station'&&<><div className="map-reminder"><Clock3 size={16}/>时间没停，还剩 {formatTime(time)}</div><div className="schematic">{(run.route??run.city.spawnStations[0].routes[0]).stops.map((name,i)=><div key={name}><i>{i===0?<LittleYou characterId={run.character.id}/>:null}</i><strong>{name}</strong>{i===(run.route??run.city.spawnStations[0].routes[0]).stops.length-1&&<b>这里下车</b>}</div>)}</div><div className="direction-answer"><Navigation size={20}/><span>首段往 <b>{(run.route??run.city.spawnStations[0].routes[0]).direction}</b></span></div>{run.route?.via&&<p className="sheet-note">在 {run.route.via} 换乘。之后跟随{run.city.stationName}标识。</p>}<p className="sheet-fine">简化的游戏线路，省略了途经站。</p></>}
 {dialog==='achievements'&&<AchievementShelf progress={progress}/>}
 {dialog==='records'&&<div className="records">{records.length?records.map(r=><div key={r.id}><span className={r.success?'record-success':'record-fail'}>{r.success?<Check size={21}/>:<X size={21}/>}</span><span><b>{r.city} · {r.title??(r.success?'赶上了！':'下次一定')}</b><small>{r.date} · {Math.round(r.elapsed)} 秒旅程</small></span><strong>{r.success?formatTime(r.margin):'差一点'}</strong></div>):<div className="no-record"><LittleYou characterId={run.character.id} motion="waiting"/><h3>还没出发，就想领奖？</h3><p>先去赶一趟，回来再说。</p></div>}<p className="sheet-fine">最近 30 次记录保存在本机。</p></div>}
 </Sheet>}
 {run.phase!=='station'&&<EventLayer run={run} dispatch={dispatch}/>}
 {notice&&<div className="small-toast" role="status">{notice}</div>}
 </div>;
}
