import { useEffect, useRef, useState } from 'react';
import { Check, MapPin, ArrowRight, TrainFront } from 'lucide-react';
import type { Run } from './engine';
export {LittleYou} from './LittleYou';
export function TinyTrain({doors=false}:{doors?:boolean}){
 return <svg viewBox="0 0 250 120" className={'tiny-train '+(doors?'doors-open':'')} aria-hidden="true"><ellipse cx="130" cy="103" rx="102" ry="8" fill="#625c4220"/><g stroke="#6a6856" strokeWidth="2.5" strokeLinejoin="round"><path d="M18 30q0-13 17-13h132q28 0 46 23l23 29q15 23-10 24H33q-15 0-15-15z" fill="#fffdf2"/><path d="M19 68h211l10 12H19z" fill="#8caf84" stroke="none"/><rect x="31" y="30" width="35" height="28" rx="8" fill="#bad7d5"/><rect x="77" y="30" width="35" height="28" rx="8" fill="#bad7d5"/><path d="M160 28h13q20 1 39 32h-52z" fill="#b4d0cd"/><path d="M41 34l-6 8m13-8-10 14m50-14-6 8m14-8-10 14m87-14 16 21" stroke="#e8f4e9" strokeWidth="2"/><g className="train-door"><rect x="125" y="29" width="23" height="63" rx="6" fill="#f4eddb"/><path d="M137 32v57" stroke="#c6c0a9" strokeWidth="1.5"/></g><path d="M218 71h10" stroke="#e7b85f" strokeWidth="5"/><circle cx="51" cy="96" r="8" fill="#858574"/><circle cx="187" cy="96" r="8" fill="#858574"/><path d="M31 21h116" stroke="#c6d6b5" strokeWidth="2"/></g><g className="passenger" transform="translate(88 43)"><path d="M-6 12q0-11 7-11t7 11" fill="#91ae92"/><circle cy="1" r="5" fill="#6f5943"/><path d="M-2-2q3-3 6 0" stroke="#a18a65" strokeWidth="1.3" fill="none"/></g><path className="train-motion-line" d="M9 51H-6m15 12H-15m24 12H-3" stroke="#bab89a" strokeWidth="2" strokeLinecap="round"/></svg>;
}
export function MetroScene({run}:{run:Run}){
 const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(700);useEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(([e])=>setWidth(e.contentRect.width));observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const stops=run.route!.stops;const trackLength=Math.max(560,(stops.length-1)*156);const trainX=run.metroProgress*trackLength;const camera=Math.min(Math.max(0,trainX+100-width*.42),Math.max(0,trackLength-width+200));const arrived=run.phase==='arrival';const next=Math.min(stops.length-1,run.metroStopIndex+(arrived?0:1));
 return <div className={'metro-scene '+(arrived?'arrived':'')} ref={ref}><div className="metro-sky"><span className="sky-cloud cloud-one"/><span className="sky-cloud cloud-two"/><span className="sun-dot"/></div><div className="far-city" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{height:46+(i*23)%83,width:24+(i*19)%37}}/>)}</div><div className="metro-destination"><span>要去的地方</span><strong><MapPin size={15}/>{run.city.stationName}</strong></div><div className="track-camera" style={{transform:'translateX('+(-camera)+'px)'}}><div className="track" style={{width:trackLength}}><div className="rail"/><div className="rail-dashes"/><div className="rolling-train" style={{left:trainX}}><div className="train-thought">{arrived?'这一站，下不下？':'留意站名，别坐过了…'}</div><TinyTrain doors={arrived}/><span className="passenger-tag">小小的你 ↑</span></div>{stops.map((name,i)=>{const passed=i<=(arrived?next-1:run.metroStopIndex);return <div key={name} className={'line-stop '+(passed?'passed ':'')+(i===next?'next ':'')+(i===stops.length-1?'destination':'')} style={{left:i/(stops.length-1)*trackLength}}><i>{passed?<Check size={11}/>:i===stops.length-1?<TrainFront size={18}/>:null}</i><span>{name}</span>{i===next&&!arrived&&<small>下一站</small>}</div>;})}</div></div><div className="metro-scene-ground"><span className="grass grass-one"/><span className="grass grass-two"/><span className="grass grass-three"/></div><div className="metro-caption">{arrived?<><span className="door-light"/>车门开了，先认清站名</>:<><span className="door-light"/>下一站快到了<ArrowRight size={14}/></>}</div></div>;
}

export function StationFloorMap({run}:{run:Run}){
 return <div className="journey-itinerary">{run.stationJourney.map((beat,i)=><div key={beat.id} className={i===run.stationBeat?'current':''}><b>{i<run.stationBeat?'✓':String(i+1).padStart(2,'0')}</b><span>{beat.label}<small>{i<run.stationBeat?'已通过':i===run.stationBeat?(run.event?'被拦住，完成操作后放行':'正在赶往这里'):'尚未到达'}</small></span></div>)}</div>;
}
