import type {Run} from './engine';
import type {Choice,EventConfig} from './data';
export type Playstyle='distance'|'queue'|'navigation'|'vertical'|'mixed';
export type StationDecision={group:string;value:string;category:Playstyle;optimal:boolean;travelScale?:number;density?:number;skip?:string[]};
export type MapNode={id:string;x:number;y:number;label:string;kind:'metro'|'entry'|'security'|'hall'|'gate'|'vertical'};
export type StationChapter={id:string;name:string;short:string;accent:string;paper:string;playstyle:Playstyle;strategy:string;feeling:string;personality:string;gate:string;walking:number;obstaclePattern:number[];nodes:MapNode[];edges:[string,string][];routes:{id:string;label:string;points:string[]}[]};
const node=(id:string,x:number,y:number,label:string,kind:MapNode['kind']):MapNode=>({id,x,y,label,kind});
export const STATIONS:StationChapter[]=[
 {id:'shanghai',name:'上海虹桥站',short:'长廊耐力赛',accent:'#a08453',paper:'#f3e6c5',playstyle:'distance',gate:'12A',walking:432,obstaclePattern:[0,1,2,1],feeling:'好像已经到了，怎么还有 300 米。',personality:'长廊口的老太太，谁赶路都要被她念两句。',strategy:'长通道别乱冲，把体力留给最后一段。',nodes:[node('metro',25,135,'地铁','metro'),node('entry',100,135,'铁路出发','entry'),node('shops',190,90,'商店通道','hall'),node('outer',190,185,'外侧长廊','hall'),node('security',285,135,'安检','security'),node('hall',355,135,'宽大厅','hall'),node('gate',455,135,'12A','gate')],edges:[['metro','entry'],['entry','shops'],['entry','outer'],['shops','security'],['outer','security'],['security','hall'],['hall','gate']],routes:[{id:'shops',label:'商店近路',points:['metro','entry','shops','security','hall','gate']},{id:'outer',label:'外侧长廊',points:['metro','entry','outer','security','hall','gate']}]},
 {id:'beijing',name:'北京南站',short:'安检观察员',accent:'#a9685c',paper:'#f0ddcd',playstyle:'queue',gate:'8A',walking:294,obstaclePattern:[1,1,0,2,1],feeling:'入口不远，队伍却一眼望不到头。',personality:'安检员严格照章办事，队伍快慢全靠观察。',strategy:'队伍短不等于快，观察行李和处理速度。',nodes:[node('metro',240,215,'地铁','metro'),node('entry',240,173,'南入口','entry'),node('west',105,155,'西侧开放','entry'),node('east',375,155,'东侧出口','entry'),node('security',105,94,'安检三队','security'),node('hall',245,62,'候车厅','hall'),node('gate',400,45,'8A','gate')],edges:[['metro','entry'],['entry','west'],['entry','east'],['west','security'],['east','west'],['security','hall'],['hall','gate']],routes:[{id:'west',label:'西侧开放入口',points:['metro','entry','west','security','hall','gate']},{id:'east',label:'东侧折返',points:['metro','entry','east','west','security','hall','gate']}]},
 {id:'guangzhou',name:'广州南站',short:'综合通路挑战',accent:'#548d83',paper:'#dbe9d4',playstyle:'mixed',gate:'16A',walking:450,obstaclePattern:[0,2,1,2,0],feeling:'又远又挤，直线未必是最快的一条。',personality:'热心旅客人人指路，答案却互相矛盾。',strategy:'把人流、换层、距离一起算，稳定通路更值。',nodes:[node('metro',50,210,'地铁','metro'),node('entry',85,150,'南区入口','entry'),node('center',245,165,'人潮近路','hall'),node('outer',115,55,'外围连桥','hall'),node('lift',330,100,'换层','vertical'),node('security',340,45,'安检','security'),node('hall',415,120,'北大厅','hall'),node('gate',450,205,'16A','gate')],edges:[['metro','entry'],['entry','center'],['entry','outer'],['center','lift'],['outer','security'],['lift','security'],['security','hall'],['hall','gate']],routes:[{id:'center',label:'中区近路＋换层',points:['metro','entry','center','lift','security','hall','gate']},{id:'outer',label:'外围稳定通路',points:['metro','entry','outer','security','hall','gate']}]},
 {id:'hangzhou',name:'杭州东站',short:'岔路读图题',accent:'#5a9291',paper:'#dceae2',playstyle:'navigation',gate:'6B',walking:276,obstaclePattern:[0,2],feeling:'并没有很远，只是每个路口都要看清。',personality:'广告、工作群、通勤人潮都在催你赶路。',strategy:'先认出发与到达，再认 B 区，别跟人流猜。',nodes:[node('metro',235,215,'地铁','metro'),node('entry',235,146,'分岔路口','entry'),node('west',95,88,'到达出口','entry'),node('east',375,88,'铁路出发','entry'),node('security',375,35,'东侧安检','security'),node('hall',235,45,'B 区连廊','hall'),node('gate',105,35,'6B','gate')],edges:[['metro','entry'],['entry','west'],['entry','east'],['west','entry'],['east','security'],['security','hall'],['hall','gate']],routes:[{id:'east',label:'东侧出发通路',points:['metro','entry','east','security','hall','gate']},{id:'west',label:'西侧出口折返',points:['metro','entry','west','entry','east','security','hall','gate']}]},
 {id:'wuhan',name:'武汉站',short:'换层规划课',accent:'#7d7da7',paper:'#e4e1ef',playstyle:'vertical',gate:'9A',walking:342,obstaclePattern:[2,1,0],feeling:'B1、1F、2F，到底哪层才上车？',personality:'这一班的柜台老板和路人都急，换层更要稳住。',strategy:'认准 2F 出发层，楼梯省时，电梯恢复体力。',nodes:[node('metro',70,210,'B1 地铁','metro'),node('entry',185,210,'中庭','entry'),node('stairs',185,125,'楼梯 / 扶梯','vertical'),node('lift',380,125,'直达电梯','vertical'),node('arrivals',75,125,'1F 到达','hall'),node('security',190,40,'2F 安检','security'),node('hall',315,40,'出发层','hall'),node('gate',445,40,'9A','gate')],edges:[['metro','entry'],['entry','stairs'],['entry','lift'],['stairs','security'],['lift','hall'],['stairs','arrivals'],['security','hall'],['hall','gate']],routes:[{id:'stairs',label:'楼梯直上 2F',points:['metro','entry','stairs','security','hall','gate']},{id:'escalator',label:'扶梯换层',points:['metro','entry','stairs','security','hall','gate']},{id:'lift',label:'电梯直达 2F',points:['metro','entry','lift','hall','gate']}]},
 {id:'zhengzhou',name:'郑州东站',short:'对称大厅找号',accent:'#ad8b45',paper:'#f1e5bf',playstyle:'navigation',gate:'21A',walking:336,obstaclePattern:[0,2,2,0,1],feeling:'两边长得一样，21A 可不是 12A。',personality:'中央大厅里的老乡太热情，停下聊两句就会误事。',strategy:'先核对车票编号，再选大厅翼区，少一次折返。',nodes:[node('metro',245,215,'地铁','metro'),node('entry',245,172,'入口','entry'),node('security',245,130,'安检','security'),node('hall',245,85,'中央大厅','hall'),node('west',80,85,'01–15 区','hall'),node('east',410,85,'16–30 区','hall'),node('wrong',80,30,'12A','gate'),node('gate',410,30,'21A','gate')],edges:[['metro','entry'],['entry','security'],['security','hall'],['hall','west'],['hall','east'],['west','wrong'],['east','gate']],routes:[{id:'east',label:'右侧 16–30 区',points:['metro','entry','security','hall','east','gate']},{id:'west',label:'左侧折返',points:['metro','entry','security','hall','west','hall','east','gate']}]}
];
// Draw once per round; choosing a card or difficulty must keep this pair.
export function drawStationPair(rng=Math.random):StationChapter[]{
 const pool=[...STATIONS];
 const first=pool.splice(Math.floor(rng()*pool.length),1)[0];
 const second=pool[Math.floor(rng()*pool.length)];
 return [first,second];
}
export function stationFor(s:Pick<Run,'city'>){return STATIONS.find(x=>x.id===s.city.id)??STATIONS[0];}
export function selectedPath(s:Run){const st=stationFor(s);return [...(s.stationDecisions??[])].reverse().find(d=>st.routes.some(r=>r.id===d.value))?.value??(s.city.id==='wuhan'?s.student?.vertical:undefined);}
const option=(label:string,detail:string,seconds:number,group:string,value:string,category:Playstyle,optimal:boolean,extra:Partial<StationDecision>={}):Choice=>({label,detail,seconds,stationDecision:{group,value,category,optimal,...extra}});
export function stationChallenge(s:Run,id:string):EventConfig|undefined{
 const common={id,phase:'station' as const,interaction:{kind:'choice' as const,seconds:15,penalty:0}};
 const who=s.character.id,energy=s.student?.stamina??s.characterTime?.energy??50;
 switch(id){
 case 'sh-corridor':return {...common,title:'长廊口的老太太把你拦住了',description:who==='worker'?'“回来上班了？拎这么多，是想在上海累坏吗？”她挡着商店近路，外侧长廊虽然远却空。':who==='tourist'?'“看你这样子，走到检票口都难吧？”她指着商店近路，旁边外侧长廊更空。':'“大学生又起晚了？这点路都赶不上？”她挡在商店通道口。',choices:[option('绕外侧长廊，保住节奏','路程 +10% · 路障更少',0,id,'outer','distance',true,{travelScale:1.1,density:1}),option('从她身边挤进商店','路程 −25% · 人群更密',0,id,'shops','distance',false,{travelScale:.75,density:3})]};
 case 'bj-entry':return {...common,title:'安检员指向开放入口：“请看牌子。”',description:who==='worker'?'老板消息还在响。东侧无人排队，却只出不进；西侧开放入口有人流。':who==='tourist'?'陌生站的两个入口长得很像。工作人员反复提醒：东侧只出不进。':'东侧看着人少，牌子却写着只出不进。工作人员不会破例。',choices:[option('按指示去西侧开放入口','直达安检排队区',0,id,'west','queue',true),option('试试人少的东侧','被拦下后折返 · +45 秒',45,id,'east','queue',false)]};
 case 'bj-tray':return {...common,title:'安检轮到你了，先把包放上托盘！',description:'按住放稳背包，让队伍继续向前。',interaction:{kind:'hold',required:2,seconds:10,penalty:0},choices:[{label:'按住放稳背包',detail:'提前整理，顺利通过',seconds:0}]};
 case 'gz-route':return {...common,title:'三个热心人同时指路，听谁的？',description:who==='tourist'?'有人说中区近，有人说外围桥空。你在陌生站里必须把距离、人流和换层一起算。':'“这边近！”“那边不用换层！”中区要穿人潮，外围连桥稍远却直接接上安检层。',choices:[option('看标识，走外围连桥','路程 +15% · 少人流 · 跳过电梯区',0,id,'outer','mixed',true,{travelScale:1.15,density:1,skip:['gz-lift']}),option('听热心人，挤中区近路','路程 −20% · 多路障 · 还需换层',0,id,'center','mixed',false,{travelScale:.8,density:3})]};
 case 'gz-lift':return {...common,title:'中区电梯排队，改走楼梯吗？',description:'电梯前排着大箱子，旁边的楼梯能通往出发层。',choices:[option('等电梯，恢复体力','等候 +45 秒 · 恢复 25 体力',45,id,'lift','mixed',energy<25),option('改走楼梯','+12 秒 · 消耗 22 体力',12,id,'stairs','mixed',energy>=25)]};
 case 'hz-fork':return {...common,title:who==='worker'?'工作群又响了，你站在出发／到达岔口':who==='tourist'?'通勤人潮很快，你跟不跟？':'路口全是赶着上班的人，你往哪走？',description:'屏幕上是工作消息，脚下却是两个方向：左边西广场／到达，右边东侧／铁路出发。先看清再动。',choices:[option('看牌，右转铁路出发','进入东侧安检',0,id,'east','navigation',true),option('跟着通勤人流左转','到达出口不通候车厅 · 折返 +45 秒',45,id,'west','navigation',false)]};
 case 'hz-zone':return {...common,title:'通勤屏和工作消息同时闪：6B 在哪廊？',description:`周围的人都盯着打卡时间。你的车票是 ${s.gate}，A 廊在左，B 廊在右，先认字母再走。`,choices:[option('右侧 B 廊','直接抵达 6B',0,id,'b','navigation',true),option('左侧 A 廊','发现字母不对再折返 · +35 秒',35,id,'a','navigation',false)]};
 case 'wh-floor':return {...common,title:'小卖部老板急着补货，推车挡住扶梯口',description:who==='worker'?'“让让！别堵着！”老板正烦躁地搬货，你拎着妈妈塞满的箱子，更得先认准楼层。':who==='tourist'?'你刚想问路，老板就催着你让道。旁边牌子写着 B1 地铁、1F 到达、2F 铁路出发。':'“要买就买，别堵路！”老板推着货车经过。先确认要去的楼层，再选上楼方式。',choices:[option('避开货车，找 2F 铁路出发','先找对层，再规划扶梯或电梯',0,id,'2f','vertical',true),option('跟着人流去 1F','到达层不能上车 · +50 秒',50,id,'1f','vertical',false)]};
 case 'zz-hometown':return {...common,title:who==='worker'?'老乡拦住你：“回来上班啦？工资多少？”':who==='tourist'?'热情老乡拦下你：“第一次来？我给你指路！”':'老乡一眼认出你的口音，非要聊两句',description:who==='worker'?'他站在中央大厅的分区牌前。不回答会被继续纠缠；说了还得决定说真话还是报低一点。':'他挡住了中央大厅的指示牌。先摆脱聊天，才能确认检票口在哪一侧。',choices:who==='worker'?[{label:'不告诉他，继续找路',detail:'被追问纠缠 30 秒',seconds:30},{label:'告诉他',detail:'还得回答一个问题',seconds:0}]:[{label:'礼貌说要赶车，先看牌',detail:'不额外耽误',seconds:0},{label:'停下来聊两句',detail:'耽误 20 秒，再看检票口',seconds:20}]};
 case 'zz-hometown-answer':return {...common,title:'老乡追问：“到底挣多少嘛？”',description:'你已经停下来了。真话可能被借钱；报低工资也未必能脱身。',choices:[{label:'说真话',detail:'老乡开口借钱 · 心力（专注）−10',seconds:0},{label:'说工资 5000',detail:'被嘲讽 · 心力（专注）−5 · 体力 +5',seconds:0}]};
 case 'zz-wing':return {...common,title:'又有人喊“老乡这边！”先看车票',description:`你的车票是 ${s.gate}。两侧长得一样：左翼 01–15，右翼 16–30。`,choices:[option('右翼 16–30','按车票数字选分区',0,id,'east','navigation',true),option('左翼 01–15','要折返中央大厅 · +55 秒',55,id,'west','navigation',false)]};
 case 'zz-number':return {...common,title:'别听身后的老乡喊，自己核对检票口',description:`车票：${s.gate}。12 和 21 很像，A、B 也不能看反。`,interaction:{kind:'gate-number',seconds:15,penalty:0},choices:['12A','21B','21A','12B','22A','11A'].map(value=>option(value,value===s.gate?'和车票一致':'走近再发现不对 · +35 秒',value===s.gate?0:35,id,value,'navigation',value===s.gate))};
 }
 return undefined;
}
