import type {Run} from './engine';
import type {Choice,EventConfig} from './data';
export type Playstyle='distance'|'queue'|'navigation'|'vertical'|'mixed';
export type StationDecision={group:string;value:string;category:Playstyle;optimal:boolean;travelScale?:number;density?:number;skip?:string[]};
export type MapNode={id:string;x:number;y:number;label:string;kind:'metro'|'entry'|'security'|'hall'|'gate'|'vertical'};
export type StationChapter={id:string;name:string;short:string;accent:string;paper:string;playstyle:Playstyle;strategy:string;feeling:string;gate:string;walking:number;obstaclePattern:number[];nodes:MapNode[];edges:[string,string][];routes:{id:string;label:string;points:string[]}[]};
const node=(id:string,x:number,y:number,label:string,kind:MapNode['kind']):MapNode=>({id,x,y,label,kind});
export const STATIONS:StationChapter[]=[
 {id:'shanghai',name:'上海虹桥站',short:'长廊耐力赛',accent:'#a08453',paper:'#f3e6c5',playstyle:'distance',gate:'12A',walking:432,obstaclePattern:[0,1,2,1],feeling:'好像已经到了，怎么还有 300 米。',strategy:'长通道别乱冲，把体力留给最后一段。',nodes:[node('metro',25,135,'地铁','metro'),node('entry',100,135,'铁路出发','entry'),node('shops',190,90,'商店通道','hall'),node('outer',190,185,'外侧长廊','hall'),node('security',285,135,'安检','security'),node('hall',355,135,'宽大厅','hall'),node('gate',455,135,'12A','gate')],edges:[['metro','entry'],['entry','shops'],['entry','outer'],['shops','security'],['outer','security'],['security','hall'],['hall','gate']],routes:[{id:'shops',label:'商店近路',points:['metro','entry','shops','security','hall','gate']},{id:'outer',label:'外侧长廊',points:['metro','entry','outer','security','hall','gate']}]},
 {id:'beijing',name:'北京南站',short:'安检观察员',accent:'#a9685c',paper:'#f0ddcd',playstyle:'queue',gate:'8A',walking:294,obstaclePattern:[1,1,0,2,1],feeling:'入口不远，队伍却一眼望不到头。',strategy:'队伍短不等于快，观察行李和处理速度。',nodes:[node('metro',240,215,'地铁','metro'),node('entry',240,173,'南入口','entry'),node('west',105,155,'西侧开放','entry'),node('east',375,155,'东侧出口','entry'),node('security',105,94,'安检三队','security'),node('hall',245,62,'候车厅','hall'),node('gate',400,45,'8A','gate')],edges:[['metro','entry'],['entry','west'],['entry','east'],['west','security'],['east','west'],['security','hall'],['hall','gate']],routes:[{id:'west',label:'西侧开放入口',points:['metro','entry','west','security','hall','gate']},{id:'east',label:'东侧折返',points:['metro','entry','east','west','security','hall','gate']}]},
 {id:'guangzhou',name:'广州南站',short:'综合通路挑战',accent:'#548d83',paper:'#dbe9d4',playstyle:'mixed',gate:'16A',walking:450,obstaclePattern:[0,2,1,2,0],feeling:'又远又挤，直线未必是最快的一条。',strategy:'把人流、换层、距离一起算，稳定通路更值。',nodes:[node('metro',50,210,'地铁','metro'),node('entry',85,150,'南区入口','entry'),node('center',245,165,'人潮近路','hall'),node('outer',115,55,'外围连桥','hall'),node('lift',330,100,'换层','vertical'),node('security',340,45,'安检','security'),node('hall',415,120,'北大厅','hall'),node('gate',450,205,'16A','gate')],edges:[['metro','entry'],['entry','center'],['entry','outer'],['center','lift'],['outer','security'],['lift','security'],['security','hall'],['hall','gate']],routes:[{id:'center',label:'中区近路＋换层',points:['metro','entry','center','lift','security','hall','gate']},{id:'outer',label:'外围稳定通路',points:['metro','entry','outer','security','hall','gate']}]},
 {id:'hangzhou',name:'杭州东站',short:'岔路读图题',accent:'#5a9291',paper:'#dceae2',playstyle:'navigation',gate:'6B',walking:276,obstaclePattern:[0,2],feeling:'并没有很远，只是每个路口都要看清。',strategy:'先认出发与到达，再认 B 区，别跟人流猜。',nodes:[node('metro',235,215,'地铁','metro'),node('entry',235,146,'分岔路口','entry'),node('west',95,88,'到达出口','entry'),node('east',375,88,'铁路出发','entry'),node('security',375,35,'东侧安检','security'),node('hall',235,45,'B 区连廊','hall'),node('gate',105,35,'6B','gate')],edges:[['metro','entry'],['entry','west'],['entry','east'],['west','entry'],['east','security'],['security','hall'],['hall','gate']],routes:[{id:'east',label:'东侧出发通路',points:['metro','entry','east','security','hall','gate']},{id:'west',label:'西侧出口折返',points:['metro','entry','west','entry','east','security','hall','gate']}]},
 {id:'wuhan',name:'武汉站',short:'换层规划课',accent:'#7d7da7',paper:'#e4e1ef',playstyle:'vertical',gate:'9A',walking:342,obstaclePattern:[2,1,0],feeling:'B1、1F、2F，到底哪层才上车？',strategy:'认准 2F 出发层，楼梯省时，电梯恢复体力。',nodes:[node('metro',70,210,'B1 地铁','metro'),node('entry',185,210,'中庭','entry'),node('stairs',185,125,'楼梯 / 扶梯','vertical'),node('lift',380,125,'直达电梯','vertical'),node('arrivals',75,125,'1F 到达','hall'),node('security',190,40,'2F 安检','security'),node('hall',315,40,'出发层','hall'),node('gate',445,40,'9A','gate')],edges:[['metro','entry'],['entry','stairs'],['entry','lift'],['stairs','security'],['lift','hall'],['stairs','arrivals'],['security','hall'],['hall','gate']],routes:[{id:'stairs',label:'楼梯直上 2F',points:['metro','entry','stairs','security','hall','gate']},{id:'escalator',label:'扶梯换层',points:['metro','entry','stairs','security','hall','gate']},{id:'lift',label:'电梯直达 2F',points:['metro','entry','lift','hall','gate']}]},
 {id:'zhengzhou',name:'郑州东站',short:'对称大厅找号',accent:'#ad8b45',paper:'#f1e5bf',playstyle:'navigation',gate:'21A',walking:336,obstaclePattern:[0,2,2,0,1],feeling:'两边长得一样，21A 可不是 12A。',strategy:'先核对车票编号，再选大厅翼区，少一次折返。',nodes:[node('metro',245,215,'地铁','metro'),node('entry',245,172,'入口','entry'),node('security',245,130,'安检','security'),node('hall',245,85,'中央大厅','hall'),node('west',80,85,'01–15 区','hall'),node('east',410,85,'16–30 区','hall'),node('wrong',80,30,'12A','gate'),node('gate',410,30,'21A','gate')],edges:[['metro','entry'],['entry','security'],['security','hall'],['hall','west'],['hall','east'],['west','wrong'],['east','gate']],routes:[{id:'east',label:'右侧 16–30 区',points:['metro','entry','security','hall','east','gate']},{id:'west',label:'左侧折返',points:['metro','entry','security','hall','west','hall','east','gate']}]}
];
// Draw once per round; choosing a card or difficulty must keep this pair.
export function drawStationPair(rng=Math.random):StationChapter[]{
 const pool=[...STATIONS];
 const first=pool.splice(Math.floor(rng()*pool.length),1)[0];
 const second=pool[Math.floor(rng()*pool.length)];
 return [first,second];
}
export function stationFor(s:Pick<Run,'city'>){return STATIONS.find(x=>x.id===s.city.id)??STATIONS[0];}
export function selectedPath(s:Run){const st=stationFor(s);return [...(s.stationDecisions??[])].reverse().find(d=>st.routes.some(r=>r.id===d.value))?.value??(s.city.id==='wuhan'?s.student?.vertical:undefined);}
const option=(label:string,detail:string,seconds:number,group:string,value:string,category:Playstyle,optimal:boolean,extra:Partial<StationDecision>={}):Choice=>({label,detail,seconds,stationDecision:{group,value,category,optimal,...extra}});
export function stationChallenge(s:Run,id:string):EventConfig|undefined{
 const common={id,phase:'station' as const,interaction:{kind:'choice' as const,seconds:15,penalty:0}};
 switch(id){
 case 'sh-corridor':return {...common,title:'近路穿商店，还是外侧长廊？',description:'中间近，但全是停下来购物的人。外侧稍远，跑道更空。',choices:[option('走外侧长廊','路程 +10% · 路障更少',0,id,'outer','distance',true,{travelScale:1.1,density:1}),option('穿过商店近路','下一段路程 −25% · 多次避让人群',0,id,'shops','distance',false,{travelScale:.75,density:3})]};
 case 'bj-entry':return {...common,title:'东侧入口，为什么没有人在进？',description:'牌子上写着：东侧只出不进，西侧入口开放。',choices:[option('去西侧开放入口','直达安检排队区',0,id,'west','queue',true),option('试试人少的东侧','需要折返西侧 · +45 秒',45,id,'east','queue',false)]};
 case 'bj-tray':return {...common,title:'安检轮到你了，先把包放上托盘！',description:'按住放稳背包，让队伍继续向前。',interaction:{kind:'hold',required:2,seconds:10,penalty:0},choices:[{label:'按住放稳背包',detail:'提前整理，顺利通过',seconds:0}]};
 case 'gz-route':return {...common,title:'近路很挤，远路绕开了换层。',description:'中区要穿人潮再换层；外围连桥稍远，但直接接上安检层。',choices:[option('外围连桥，稳稳通过','下一段路程 +15% · 少人流 · 跳过电梯区',0,id,'outer','mixed',true,{travelScale:1.15,density:1,skip:['gz-lift']}),option('中区近路，穿过人潮','下一段路程 −20% · 多路障 · 还需换层',0,id,'center','mixed',false,{travelScale:.8,density:3})]};
 case 'gz-lift':return {...common,title:'中区电梯排队，改走楼梯吗？',description:'电梯前排着大箱子，旁边的楼梯能通往出发层。',choices:[option('等电梯，恢复体力','等候 +45 秒 · 恢复 25 体力',45,id,'lift','mixed',s.student!.stamina<25),option('改走楼梯','+12 秒 · 消耗 22 体力',12,id,'stairs','mixed',s.student!.stamina>=25)]};
 case 'hz-fork':return {...common,title:'西边到达，东边出发。你往哪走？',description:'左箭头：西广场／到达；右箭头：东侧／铁路出发。高铁在出发区。',choices:[option('右转，铁路出发','进入东侧安检',0,id,'east','navigation',true),option('左转，跟着出站人流','到达出口不通候车厅 · 折返 +45 秒',45,id,'west','navigation',false)]};
 case 'hz-zone':return {...common,title:'6B，要进 A 廊还是 B 廊？',description:`车票检票口 ${s.gate}。A 廊在左，B 廊在右，两个入口离得很近。`,choices:[option('右侧 B 廊','直接抵达 6B',0,id,'b','navigation',true),option('左侧 A 廊','发现字母不对再折返 · +35 秒',35,id,'a','navigation',false)]};
 case 'wh-floor':return {...common,title:'先认楼层：你要去几楼？',description:'B1 地铁｜1F 到达｜2F 铁路出发。中庭里的楼层牌不能看漏。',choices:[option('2F 铁路出发','找上楼通路',0,id,'2f','vertical',true),option('1F 大厅，看着人多','走到到达层再上楼 · +50 秒',50,id,'1f','vertical',false)]};
 case 'zz-wing':return {...common,title:'对称大厅，往哪一边找检票口？',description:`你的车票是 ${s.gate}。左翼 01–15，右翼 16–30。`,choices:[option('右翼 16–30','按车票数字选分区',0,id,'east','navigation',true),option('左翼 01–15','要折返中央大厅 · +55 秒',55,id,'west','navigation',false)]};
 case 'zz-number':return {...common,title:'看清数字和字母，点出你的检票口。',description:`车票：${s.gate}。12 和 21 很像，A、B 也不能看反。`,interaction:{kind:'gate-number',seconds:15,penalty:0},choices:['12A','21B','21A','12B','22A','11A'].map(value=>option(value,value===s.gate?'和车票一致':'走近再发现不对 · +35 秒',value===s.gate?0:35,id,value,'navigation',value===s.gate))};
 }
 return undefined;
}
