import {PREPARATION_BALANCE as PREP} from './preparationConfig';
import ChoiceDetail from './ChoiceDetail';
import {useStationAction} from './StationActionContext';
import PreparationFrame from './PreparationFrame';
import {useState,useEffect,type Dispatch} from 'react';
import {Backpack,Zap,ArrowRight} from 'lucide-react';
import {PREPARATIONS,POCKETS,STUDENT,bagHint,focusWindow} from './studentConfig';
import {timedPrompt,characterTimeProfiles} from './characterTime';
import {formatTime,journeyRouteSeconds,type Run,type Action} from './engine';
import HoldAction from './HoldAction';
import {stationFor} from './stations';
export function Preparation({run,dispatch}:{run:Run;dispatch:Dispatch<Action>}){
 const u=run.student!,p=PREPARATIONS[u.prep];
 const detail=(o:typeof p.options[number])=>{if(p.id!=='breakfast'||o.id!=='eat')return o.detail;const gain=Math.max(0,Math.min(100,u.stats.energy+(o.stats?.energy??0))-u.stats.energy);return `−${o.seconds} 秒 · ${gain?'精力上限 +'+gain:'精力已满'} · 吃饱，后半程脚步稳`;};
 const stats=<div className="student-stats">{(['agility','energy','focus','load'] as const).map((k,i)=><span key={k}>{['敏捷','体力','专注','负重'][i]}<b>{'●'.repeat(Math.round(u.stats[k]/20))}{'○'.repeat(5-Math.round(u.stats[k]/20))}</b></span>)}</div>;
 return <PreparationFrame run={run} step={u.prep} title={p.title} story={p.story} stats={stats} note="想一想也在花时间。准备得好，后面会轻松些。">
  <div className="event-buttons">{p.options.map(o=><button className="soft-action" key={o.id} onClick={()=>dispatch({type:'PREP_PICK',option:o.id,step:u.prep})}><span><strong>{o.label}</strong><ChoiceDetail text={detail(o)}/></span><ArrowRight size={20}/></button>)}</div>
 </PreparationFrame>;
}
export function CharacterPreparation({run,dispatch}:{run:Run;dispatch:Dispatch<Action>}){
 const t=run.characterTime!,p=timedPrompt(run)!;
 const stats=<div className="student-stats"><span>{t.characterId==='worker'?'体力':'精力'}<b>{Math.round(t.energy)} / {t.maxEnergy}</b></span><span>疲劳<b>{Math.round(t.fatigue)} / 100</b></span><span>负重<b>{Math.round(t.load)} / 100</b></span><span>专注<b>{Math.round(t.focus)} / 100</b></span></div>;
 return <PreparationFrame className="character-preparation" run={run} step={t.prepStep} title={p.title} story={p.story} stats={stats} note={`这段选择会改变出发时的倒计时、${t.characterId==='worker'?'体力':'精力'}和赶路速度。`}>
  <div className="event-buttons">{p.choices.map(c=><button className="soft-action" key={c.id} onClick={()=>dispatch({type:'PERSON_PICK',option:c.id,step:t.prepStep})}><span><strong>{c.label}</strong><ChoiceDetail text={c.detail}/></span><ArrowRight size={20}/></button>)}</div>
 </PreparationFrame>;
}
export function StudentEnergy({run,dispatch}:{run:Run;dispatch:Dispatch<Action>}){if(run.characterTime){const t=run.characterTime,p=characterTimeProfiles[t.characterId];return <div className="student-energy character-energy"><div><Zap size={15}/><b>{t.characterId==='worker'?'体力':'精力'} {Math.ceil(t.energy)} / {t.maxEnergy}</b><span>{t.characterId==='worker'?t.prepStep>=2&&!t.ateBeforeLeaving?'空腹拖箱子，脚步慢一些':t.bossUnread?'老板还在催消息；分点专注赶路':'妈妈送的土特产增加了负重':t.fatigue>=65?'疲劳 '+Math.round(t.fatigue)+' · 精力恢复很慢':t.sprinting?'冲刺中，精力下降更快':'走路恢复很少，陌生站点多看指示'}</span></div><meter min={0} max={t.maxEnergy} value={t.energy}/><small>负重 {Math.round(t.load)} · 疲劳 {Math.round(t.fatigue)} · {t.exhausted?(t.characterId==='worker'?'体力耗尽，无法冲刺':'精力耗尽，无法冲刺'):`普通速度 ${p.baseSpeed.toFixed(2)} 倍`}</small></div>;}const u=run.student!;return <div className="student-energy"><div><Zap size={15}/><b>体力 {Math.ceil(u.stamina)} / {u.stats.energy}</b><span>{u.exhausted?'跑不动了，恢复到 15 再冲':u.sprintStrain>=4.5?'快岔气了！松开冲刺，走路调整呼吸':u.sprinting&&u.sprintStrain>3?'冲久了，速度在下降，松开调整呼吸':u.hungry?'空腹脚步慢了 · 精力上限 −10':u.sprinting?'正在消耗体力':run.stationMap?.block?'提着包挤在人群里，腾出通路后再调整呼吸':'走路慢慢恢复，停下恢复更快'}</span></div><meter min={0} max={u.stats.energy} value={u.stamina}/><small>冲刺负荷 {Math.ceil(u.sprintStrain)} / {STUDENT.breathLimit} · 短冲更快，久冲掉速；走路或停下可缓解</small>{u.cake&&<small>小蛋糕占一只手 · 走路也要护着，冲刺更费体力</small>}{u.late&&<small>最后一段短冲更快 · 恢复 +25%</small>}</div>;}
export function StudentBag({run,dispatch}:{run:Run;dispatch:Dispatch<Action>}){
 const u=run.student!;const [selected,setSelected]=useState<number|null>(null),[flash,setFlash]=useState(true);const reportAction=useStationAction();
 useEffect(()=>{const t=setTimeout(()=>setFlash(false),1500);return()=>clearTimeout(t);},[]);
 const hint=u.checkedID?'已检查 · 前袋':u.stats.focus>=75?'回忆起了位置':u.stats.focus>=55?'还有一点印象':'慢慢找，别慌';
 return <div className="student-bag"><div className="bag-heading"><Backpack size={35}/><span><b>我的双肩包</b><small>{hint}</small></span></div><p>{bagHint(u)}</p><div className="pocket-grid">{POCKETS.map((name,i)=><button className={(selected===i?'selected ':'')+(flash&&u.stats.focus>=75&&i===u.pocket?'highlight':'')} key={name} disabled={u.searched.includes(i)} onClick={()=>{setSelected(i);reportAction({progress:0,active:false,label:'准备翻找'+name});}}><span>{['🪪','💧','🎧','💻'][i]}</span><b>{name}</b><small>{u.searched.includes(i)?'找过了，不在这儿':u.checkedID&&i===0?'记得，就放在这里':'打开翻找'}</small></button>)}</div>{selected!==null&&!u.searched.includes(selected)&&<HoldAction key={selected+':'+u.bagMistakes} seconds={(u.checkedID ? .65 : 1.4)/focusWindow(u.stats.focus)*(u.cake?1.25:1)} label={u.checkedID?'取出身份证':'按住翻找'+POCKETS[selected]} onComplete={()=>{reportAction({progress:selected===u.pocket?1:0,active:false,label:selected===u.pocket?'身份证找到了！':POCKETS[selected]+'里没有，换个夹层'});dispatch({type:'POCKET_PICK',pocket:selected});setSelected(null);}}/>}<p role="status">{u.bagMistakes?`翻错 ${u.bagMistakes} 次，每次耽误 5 秒。找过的地方不用再翻。`:'先选夹层，再按住翻找。时间一直在走。'}</p></div>;
}
export function StudentReport({run}:{run:Run}){
 const u=run.student!;const spent=run.initial-run.remaining;const routeBase=run.route?journeyRouteSeconds(run,run.route):0;const best=Math.min(...run.city.spawnStations[run.spawn].routes.map(r=>journeyRouteSeconds(run,r)));const efficiency=!run.route?'尚未选线':u.wrongTurns+run.metroMisses? (u.wrongTurns+run.metroMisses<3?'B':'C'):routeBase<=best*1.1?'A':routeBase<=best*1.25?'B':'C';
 return <section className="student-report"><h3>时间花在哪里了？</h3><p className="result-explanation">{u.wrongTurns+run.metroMisses===0?'你没有走错路。路线评分只评价路线判断，赶车还要计算准备、通行和操作时间。':'路线和到站判断有绕路，下次可以提前确认。'}{!run.success?'下面把本局的时间全部展开，方便看清原因。':''}</p><div className="time-ledger">{[['地铁与换乘路程',u.clockSpent.journey],['站内前进',u.clockSpent.moving],['读题与处理事件',u.clockSpent.handling],['出发选择、休息与其他等待',u.clockSpent.waiting],['准备、排队与其他主动选择',u.decisionLoss],['人群、安检和扶梯等环境等待',u.environmentLoss]].map(([label,value])=><div key={label}><span>{label}</span><b>{formatTime(Number(value))}</b></div>)}</div><div className="report-grid"><span>路线判断<b>{efficiency}</b></span><span>走错 / 坐过站<b>{u.wrongTurns+run.metroMisses} 次</b></span><span>避开路障<b>{u.runner.dodges} 次</b></span><span>被路障拦停<b>{u.runner.collisions} 次</b></span><span>冲刺占赶路时间<b>{Math.round(u.sprintSeconds/Math.max(1,u.movingSeconds)*100)}%</b></span><span>冲刺追回约<b>{formatTime(u.sprintSaved)}</b></span><span>冲太猛岔气<b>{u.breathStops} 次</b></span><span>主动选择额外用时<b>{formatTime(u.decisionLoss)}</b></span><span>环境额外耽误<b>{formatTime(u.environmentLoss)}</b></span><span>换乘操作<b>{!run.route?'尚未选线':run.route.transfers?formatTime(u.transferSeconds):'本次直达'}</b></span><span>换乘表现<b>{!run.route?'尚未选线':run.route.transfers?(u.transferSeconds<=24?'优秀':u.transferSeconds<=48?'一般':'较慢'):'无需换乘'}</b></span><span>路线＋站内步行参考<b>{formatTime(routeBase+stationFor(run).walking)}</b></span><span>本局已用游戏时间<b>{formatTime(spent)}</b></span></div><p>{run.identityReady?'身份证已找到。':'尚未完成身份证查找。'}搜索用时：{formatTime(u.bagSeconds)} · 翻错 {u.bagMistakes} 次。{u.checkedID?`出门前花 ${PREP.identitySeconds} 秒检查，取证时不用猜位置。`:'出门前没检查，下次可以先放进前袋。'}</p><p>{u.breakfast?'吃过饭团，后半程保持精力。':u.hungry?'空腹进入大厅，精力上限下降了 10，脚步也慢了。':'没吃早餐，还未走到会饥饿的后半程。'}{u.choices.cake==='take'?'花 75 秒拿了朋友的小蛋糕，专注 +5、负重 +5；一路护着盒子，会持续耗体力、拖慢双手操作。':'没带小蛋糕，和朋友伤心地分开，专注 −5。'}</p><p>提前靠门节省 {u.doorSavings} 秒。{u.breathStops?`连续冲刺岔气 ${u.breathStops} 次，每次被迫停下 ${STUDENT.breathPenalty} 秒。`:'没有因连续冲刺岔气。'}{u.wrongTurns?'下次先认路牌，别只跟着人群跑。':'看清方向，就是在给最后冲刺留时间。'}</p><small>本局总耗时由上方六类组成，显示到秒时可能有取整差异。基础参考不含准备、事件和等待。冲刺能追回时间；路线、队伍和操作同样决定能否赶上。</small></section>;
}
