import type {RunnerState} from './runner';
import type {CityConfig, EventConfig} from './data';
export type Stats={agility:number;energy:number;focus:number;load:number};
export const STUDENT={id:'student',baseStats:{agility:80,energy:90,focus:55,load:15} as Stats,badLuckBudget:180,lateThreshold:120,sprintMultiplier:1.9,lateSprint:1.15,lateRecovery:1.25,drain:8,recover:5,walkRecover:2.2,breathLimit:7,breathPenalty:105,cakeWalkDrain:2.7,cakeSprintDrain:2.2};
export const HONGQIAO={id:'shanghai-hongqiao',modifiers:{distance:1.2,crowd:1.1,security:1,navigation:1.05,verticalMovement:1},initial:35*60+30,hardReduction:360,studentHardReduction:120,normalStationTime:600,baseWalkingTime:360,metroTimeRatio:.42,transferWalkRatio:.65};
export type Preparation={id:string;title:string;story:string;options:{id:string;label:string;detail:string;seconds:number;stats?:Partial<Stats>}[]};
export const PREPARATIONS:Preparation[]=[
 {id:'cake',title:'朋友打包好的小蛋糕，要不要带上？',story:'朋友捧着蛋糕盒等你来拿。车站就在前面，你得赶紧和朋友告别。',options:[{id:'take',label:'带上小蛋糕',detail:'−75 秒 · 专注 +5、负重 +5；占一只手，赶路更费体力',seconds:75,stats:{focus:5,load:5}},{id:'skip',label:'不带，和朋友伤心地分开',detail:'专注 −5 · 舍不得朋友，有点走神',seconds:0,stats:{focus:-5}}]},
 {id:'id',title:'身份证，真的在包里吗？',story:'你摸了一下书包。“昨天好像放进去了……”',options:[{id:'skip',label:'先跑到检票口再说吧',detail:'检票时要翻包 · 位置没确认，要自己找',seconds:0},{id:'check',label:'检查好，放进前袋',detail:'−30 秒 · 专注 +10；记住前袋的位置，检票时直接取出',seconds:30,stats:{focus:10}}]},
 {id:'breakfast',title:'早餐还没吃，肚子先叫了。',story:'便利店就在旁边，还有温热的饭团。',options:[{id:'eat',label:'买个饭团，吃完再走',detail:'−60 秒 · 精力上限 +15 · 吃饱，后半程不会挨饿',seconds:60,stats:{energy:15}},{id:'skip',label:'直接走，上车再吃',detail:'精力上限 −10 · 到候车大厅后生效，后半程更容易跑不动',seconds:0}]}
];
export const POCKETS=['前袋','侧袋','主袋','电脑夹层'];
export type StudentState={eventTime:Record<string,number>;lateSprintSaved:number;exhaustedLateSeconds:number;runner:RunnerState;clockSpent:{journey:number;moving:number;handling:number;waiting:number};stats:Stats;prep:number;choices:Record<string,string>;cake:boolean;checkedID:boolean;breakfast:boolean;hungry:boolean;late:boolean;elapsedGame:number;stamina:number;exhausted:boolean;sprinting:boolean;sprintStrain:number;breathStops:number;doorReady:boolean;doorSavings:number;vertical:'escalator'|'stairs'|'lift';pocket:number;searched:number[];mapRead:boolean;observed:boolean;bagSeconds:number;bagMistakes:number;sprintSeconds:number;movingSeconds:number;sprintSaved:number;decisionLoss:number;environmentLoss:number;wrongTurns:number;stationStart:number;transferSeconds:number;queues:{people:number;seconds:number;hint:string}[]};
export function studentState(rng:()=>number):StudentState{const offset=Math.floor(rng()*3);return {eventTime:{},lateSprintSaved:0,exhaustedLateSeconds:0,runner:{lane:1,wave:0,blocked:false,collisions:0,dodges:0,seed:Math.floor(rng()*3)},clockSpent:{journey:0,moving:0,handling:0,waiting:0},stats:{...STUDENT.baseStats},prep:0,choices:{},cake:false,checkedID:false,breakfast:false,hungry:false,late:false,elapsedGame:0,stamina:STUDENT.baseStats.energy,exhausted:false,sprinting:false,sprintStrain:0,breathStops:0,doorReady:false,doorSavings:0,vertical:'escalator',pocket:Math.floor(rng()*4),searched:[],mapRead:false,observed:false,bagSeconds:0,bagMistakes:0,sprintSeconds:0,movingSeconds:0,sprintSaved:0,decisionLoss:0,environmentLoss:0,wrongTurns:0,stationStart:0,transferSeconds:0,queues:[{people:6,seconds:24,hint:'前面只背小包，托盘已摆好'},{people:3,seconds:55,hint:'一家人带着几只箱子，正打开侧袋'},{people:8,seconds:32,hint:'队列长一些，两台机器都亮着灯'}].map((_,i,arr)=>arr[(i+offset)%arr.length])};}
export function gameShanghai(city:CityConfig):CityConfig{return {...city,spawnStations:city.spawnStations.map(p=>({...p,routes:p.routes.map(r=>({...r,minutes:Math.round(r.minutes*HONGQIAO.metroTimeRatio),walk:r.transfers?Math.round(r.walk*HONGQIAO.transferWalkRatio):r.walk}))}))};}
export function movementFactor(u:StudentState){const base=(.65+u.stats.agility/100*.4667)/(1+(u.stats.load-15)*.006);return base*(u.sprinting&&!u.exhausted?STUDENT.sprintMultiplier*(u.late?STUDENT.lateSprint:1):u.exhausted?.85:1);}
export function focusWindow(focus:number){return .7+focus/100*.6;}
export function bagHint(u:StudentState){if(u.checkedID)return '出门前检查过：身份证就在前袋。';if(u.stats.focus>=75)return '刚才回想起来了，留意亮起的夹层。';if(u.stats.focus>=55)return `还记得：${u.pocket<2?'在一个外侧小袋里':'应该和大件物品放在一起'}。`;if(u.stats.focus>=35)return '记不清了，一层一层翻。';return '不会没带吧……先把每个夹层都找一遍。';}
export function studentPrompt(id:string,u:StudentState,gate='12A'):EventConfig|undefined{
 const base={id,phase:'station' as const,interaction:{kind:'choice' as const,seconds:12,penalty:0}};
 if(id==='vertical-choice')return {...base,title:'上出发层，走哪条路？',description:'背包可以走楼梯。快不快，还要看你的体力。',choices:[{label:'去扶梯口',detail:'三部扶梯，选好后才能看清拥堵情况',seconds:0,studentEffect:'escalator'},{label:'跑楼梯近路',detail:'连点上楼 · 消耗 22 体力 · 双手操作',seconds:0,studentEffect:'stairs'},{label:'等直达电梯',detail:'等待电梯 −35 秒 · 站着恢复体力',seconds:35,studentEffect:'lift'}]};
 if(id==='escalator-ride'&&u.vertical!=='escalator')return {...base,title:u.vertical==='stairs'?'扶好背包，一步步上楼！':'电梯到了，按住开门键进电梯。',description:u.vertical==='stairs'?'连续点击八次。体力不足时需要更多步，手拎蛋糕盒还要腾出手。':'进电梯需要双手收好背包。',interaction:{kind:u.vertical==='stairs'?'tap':'hold',required:u.vertical==='stairs'?(u.stamina<22?12:8)+(u.cake?2:0):u.cake?3:2,seconds:14,penalty:0},choices:[{label:'上到出发层',detail:'完成操作才继续',seconds:0}]};
 if(id==='security-queue')return {...base,title:'安检队伍，短的就一定快吗？',description:'先看人数，也可以花时间观察行李和通行速度。',choices:u.queues.map((q,i)=>({label:String.fromCharCode(65+i)+' 队 · '+q.people+' 人',detail:u.observed||u.stats.focus>=75?q.hint:'队伍里有什么？再看仔细一点',seconds:Math.round(q.seconds*HONGQIAO.modifiers.security),studentEffect:'queue'}))};
 if(id==='station-sign'){const left=parseInt(gate)<=15;return {...base,title:`候车大厅到了，${gate} 在哪边？`,description:`车票 ${gate}。头顶标识：← 1–15 号区域 ｜ 16–30 号区域 →。${u.mapRead?(left?'已经记住：左侧 1–15 号区域。':'已经记住：右侧 16–30 号区域。'):''}`,choices:[{label:left?'左转，去 1–15 区':'右转，去 16–30 区',detail:'沿检票口数字指示走',seconds:0},{label:left?'右转，跟着人群走':'左转，跟着人群走',detail:'先走过去找找',seconds:55,studentEffect:'wrong-turn'}]};}

 return undefined;
}
