import type {GameResult} from './gameResult';
import type {CharacterId} from './resultMetrics';
export interface TitleConfig{id:string;name:string;result:'success'|'failure'|'any';priority:number;characterId?:CharacterId;rarity:number;tieBreakOrder:number;condition:(r:GameResult)=>boolean;decisive?:(r:GameResult)=>boolean}
const flag=(r:GameResult,k:string)=>r.characterStats[k]===true;
const value=(r:GameResult,k:string)=>Number(r.characterStats[k]??0);
export const decisiveEvent=(r:GameResult,pattern:RegExp)=>r.timeImpacts.some(i=>i.decisive&&pattern.test(i.eventId??i.id));
const loss=(r:GameResult,category:string)=>r.timeImpacts.filter(i=>i.category===category&&i.deltaSeconds<0).reduce((t,i)=>t-i.deltaSeconds,0);
const mainLoss=(r:GameResult,pattern:RegExp)=>{const all=r.timeImpacts.filter(i=>i.deltaSeconds<0).sort((a,b)=>a.deltaSeconds-b.deltaSeconds);return !!all[0]&&pattern.test(all[0].eventId??all[0].id);};
let order=0;
const title=(id:string,name:string,result:TitleConfig['result'],priority:number,condition:TitleConfig['condition'],characterId?:CharacterId,decisive?:TitleConfig['decisive']):TitleConfig=>({id,name,result,priority,condition,characterId,decisive,rarity:priority,tieBreakOrder:order++});
export const TITLE_CONFIGS:TitleConfig[]=[
 title('disaster','这都能赶上？','success',1030,r=>r.dramaScore>=100),
 title('mother_wet','车赶上了，裤子没赶上','success',1040,r=>flag(r,'wetPants'),'mother'),
 title('family_tough','这家人命真硬','success',1020,r=>value(r,'negativeSystems')>=3,'family'),
 title('last_second','最后一秒选手','success',950,r=>r.resultMarginSeconds<=3),
 title('clutch','压哨上车王','success',940,r=>r.resultMarginSeconds<=10),
 title('heartbeat','心脏还好吗','success',930,r=>r.resultMarginSeconds<=30),
 title('one_second_late','真就差一秒','failure',960,r=>Math.abs(r.resultMarginSeconds)<=1),
 title('door_close','车门就在眼前','failure',950,r=>r.position.distanceToGoalMeters!==undefined&&r.position.distanceToGoalMeters<20),
 title('almost','就差一点','failure',940,r=>Math.abs(r.resultMarginSeconds)<=20),
 title('breath','差这一口气','failure',920,r=>r.position.distanceToGoalMeters!==undefined&&r.position.distanceToGoalMeters<50),
 title('student_clock','大学生的时间观','success',875,r=>flag(r,'tea')&&flag(r,'breakfast')&&r.errors>0,'student'),
 title('student_theory','理论上果然来得及','success',870,r=>r.initialMarginRatio!==null&&r.initialMarginRatio<.1,'student'),
 title('student_runner','年轻就是能跑','success',860,r=>value(r,'lateSprintSaved')>=20&&decisiveEvent(r,/sprint-late/),'student'),
 title('student_management','极限时间管理大师','success',845,r=>value(r,'extraPreparationSeconds')>=120&&r.resultMarginSeconds<120,'student'),
 title('student_tea','奶茶党永不认输','success',830,r=>flag(r,'tea'),'student'),
 title('student_food','吃完再走也来得及','success',820,r=>flag(r,'breakfast'),'student'),
 title('student_bag','包里有谱','success',810,r=>flag(r,'checkedID')&&flag(r,'idFound'),'student'),
 title('student_bag_wrong','包里到底装了什么','failure',870,r=>value(r,'bagMistakes')>=3,'student'),
 title('student_id','身份证去哪了','failure',860,r=>decisiveEvent(r,/identity/)||r.timeImpacts.filter(i=>i.deltaSeconds<0).sort((a,b)=>a.deltaSeconds-b.deltaSeconds).slice(0,2).some(i=>i.eventId==='identity-search'&&i.deltaSeconds<=-10),'student',r=>decisiveEvent(r,/identity/)),
 title('student_tea_loss','奶茶误我','failure',840,r=>flag(r,'tea')&&decisiveEvent(r,/prepare-tea/)&&Math.abs(r.resultMarginSeconds)<=120,'student',r=>decisiveEvent(r,/prepare-tea/)),
 title('student_food_loss','饭团的代价','failure',830,r=>flag(r,'breakfast')&&decisiveEvent(r,/prepare-breakfast/)&&Math.abs(r.resultMarginSeconds)<=60,'student'),
 title('student_bed','再躺五分钟的后果','failure',806,r=>Math.abs(r.resultMarginSeconds)<=30,'student'),
 title('student_theory_loss','理论计算失败','failure',805,r=>r.initialMarginRatio!==null&&r.initialMarginRatio<.1,'student'),
 title('worker_gifts','土特产也不能拦我','success',840,r=>flag(r,'localGifts'),'worker'),
 title('worker_focus','打工人的职业本能','success',830,r=>value(r,'focusSavings')>=30,'worker'),
 title('worker_holiday','人回去了，魂还在放假','success',820,r=>flag(r,'ignoredWork')||value(r,'workDelay')>0,'worker'),
 title('worker_buff','班味驱动','success',850,r=>flag(r,'workBuffDecisive'),'worker'),
 title('worker_basic','明天还能准时打卡','success',100,r=>r.resultMarginSeconds>120,'worker'),
 title('worker_load','土特产拖了后腿','failure',850,r=>flag(r,'loadDecisive'),'worker'),
 title('worker_message','老板消息害人','failure',840,r=>flag(r,'workDecisive'),'worker'),
 title('worker_events','人还没回去，班先上了','failure',820,r=>value(r,'workEvents')>=2,'worker'),
 title('worker_far','假期延长一天','failure',150,r=>(r.position.distanceToGoalMeters??0)>300,'worker'),
 title('worker_default','果然不该回去上班','failure',50,()=>true,'worker'),
 title('tourist_sleep','地铁也是酒店','success',830,r=>value(r,'sleepRecovery')>=25,'tourist'),
 title('tourist_alarm','睡醒刚好到','success',840,r=>flag(r,'alarmSet')&&flag(r,'slept')&&r.missedStops===0,'tourist'),
 title('tourist_low','两万步以后还能跑','success',820,r=>value(r,'initialEnergy')>0&&value(r,'initialEnergy')<=25,'tourist'),
 title('tourist_coffee','咖啡续命成功','success',850,r=>flag(r,'coffeeDecisive'),'tourist'),
 title('tourist_default','红眼车幸存者','success',50,()=>true,'tourist'),
 title('tourist_miss','真睡过站了','failure',850,r=>flag(r,'slept')&&r.missedStops>0,'tourist'),
 title('tourist_coffee_loss','咖啡也救不了','failure',840,r=>flag(r,'coffee')&&flag(r,'fatigueDecisive'),'tourist'),
 title('tourist_fatigue','眼睛睁不开了','failure',830,r=>flag(r,'fatigueDecisive'),'tourist'),
 title('tourist_walk','今天真的走不动了','failure',810,r=>value(r,'lowEnergySeconds')>=30,'tourist'),
 title('tourist_failed','红眼车受害者','failure',50,()=>true,'tourist'),
 title('mother_toilet','厕所也没拦住我们','success',840,r=>flag(r,'childToilet'),'mother'),
 title('mother_carry','一手孩子一手车票','success',830,r=>flag(r,'carriedChild'),'mother'),
 title('mother_route','妈妈路线规划师','success',810,r=>r.wrongTurns===0&&r.routeEfficiency>=90,'mother'),
 title('mother_together','一个都不能掉队','success',805,r=>flag(r,'childNeverSeparated'),'mother'),
 title('mother_clutch','车赶上了，娃也在','success',945,r=>r.resultMarginSeconds<=10,'mother'),
 title('mother_default','带娃也能上车','success',50,()=>true,'mother'),
 title('mother_wet_loss','尿意战胜了高铁','failure',875,r=>flag(r,'wetPants'),'mother'),
 title('mother_patience','孩子说不走了','failure',860,r=>flag(r,'patienceDecisive'),'mother'),
 title('mother_toilet_loss','终究还是去了厕所','failure',850,r=>flag(r,'toiletDecisive'),'mother'),
 title('mother_carry_loss','今天真的带不动了','failure',840,r=>flag(r,'carryExhausted'),'mother'),
 title('mother_loss','妈妈已经尽力了','failure',50,()=>true,'mother'),
 title('family_forgot','什么都带了，也赶上了','success',850,r=>value(r,'retrievedItems')>=2,'family'),
 title('family_access','无障碍路线大师','success',840,r=>value(r,'accessibleCorrect')>=2&&value(r,'accessibleErrors')===0,'family'),
 title('family_load','两个大箱子也能上','success',830,r=>value(r,'load')>=75,'family'),
 title('family_stroller','推车如风','success',820,r=>flag(r,'strollerOpen')&&r.routeEfficiency>=90,'family'),
 title('family_sprint','全家一起狂奔','success',860,r=>value(r,'lateSprintSaved')>=30,'family'),
 title('family_default','一家人整整齐齐','success',50,()=>true,'family'),
 title('family_collapse','今天就不该出门','failure',870,r=>value(r,'negativeSystems')>=3,'family'),
 title('family_access_loss','婴儿车无路可走','failure',850,r=>value(r,'accessibleErrors')>0,'family'),
 title('family_forgot_loss','忘的东西太多了','failure',840,r=>value(r,'forgottenDelay')>=180,'family'),
 title('family_load_loss','箱子比人先累了','failure',830,r=>flag(r,'loadDecisive'),'family'),
 title('family_default_loss','全家一起踩线失败','failure',50,()=>true,'family'),
 title('security_loss','栽在安检口','failure',760,r=>mainLoss(r,/security|gates|bj-tray/),undefined,r=>decisiveEvent(r,/security|gates/)),
 title('short_queue','短队不一定快','failure',770,r=>flag(r,'shortSlowQueue')&&decisiveEvent(r,/security-queue/)),
 title('lift_loss','电梯害人','failure',750,r=>mainLoss(r,/lift|vertical-choice/)||decisiveEvent(r,/lift|vertical-choice/)),
 title('early_sprint','前面冲太猛了','failure',740,r=>r.finalEnergy===0&&value(r,'earlySprintSeconds')>=20),
 title('low_energy','腿已经不是自己的了','failure',730,r=>value(r,'lowEnergySeconds')>=30),
 title('map_loss','地图还是得看','failure',720,r=>r.wrongTurns>=2&&r.mapViews===0),
 title('hesitation','犹豫就会败北','failure',710,r=>r.timeImpacts.some(i=>i.id.startsWith('handling-')&&i.deltaSeconds<=-60)),
 title('sprint_god','冲刺之神','success',680,r=>value(r,'lateSprintSaved')>=30),
 title('legs','腿比导航靠谱','success',670,r=>[...r.timeImpacts].filter(i=>i.positive).sort((a,b)=>b.deltaSeconds-a.deltaSeconds)[0]?.category==='movement'),
 title('optimal','没有一秒白跑','success',660,r=>r.routeEfficiency>=95&&r.errors===0),
 title('route_master','路线大师','success',650,r=>r.wrongTurns===0&&r.routeEfficiency>=90),
 title('perfect','零失误赶车人','success',640,r=>r.errors===0),
 title('comeback','逆风翻盘','success',620,r=>r.wasProjectedToFail),
 title('planning','计划通','success',630,r=>r.timeImpacts.filter(i=>i.category==='decision').reduce((t,i)=>t+i.deltaSeconds,0)>=60),
 title('gamble','赌狗成功','success',610,r=>r.highRiskResults.length>=2&&r.highRiskResults.every(Boolean)),
 title('stable','保守派的胜利','success',600,r=>r.stableChoices>=2),
 title('drama','一路翻车也上了','success',550,r=>r.dramaScore>=80||r.errors>=3),
 title('relaxed','从容上车','success',490,r=>r.resultMarginSeconds>=300),
 title('green','一路绿灯','success',410,r=>r.environmentDelaySeconds<30),
 title('navigation_loss','路线选错了','failure',490,r=>loss(r,'navigation')>0&&loss(r,'navigation')>=Math.max(loss(r,'decision'),loss(r,'operation'))),
 title('detour','多跑的每一步都算数','failure',480,r=>loss(r,'navigation')>=60),
 title('direction','看错方向了','failure',470,r=>r.wrongTurns>0||r.wrongDirections>0),
 title('optional_delay','早知道不折腾了','failure',460,r=>value(r,'extraPreparationSeconds')>=120),
 title('bad_luck','今天不宜赶车','failure',705,r=>r.timeImpacts.some(i=>!i.avoidable&&i.deltaSeconds<=-60)&&r.errors===0),
 title('success_default','赶上了','success',0,()=>true),
 title('failure_default','下次早点出门吧','failure',0,()=>true)
];
export function selectTitle(r:GameResult):TitleConfig{
 return TITLE_CONFIGS.filter(t=>(t.result==='any'||t.result===(r.success?'success':'failure'))&&(!t.characterId||t.characterId===r.characterId)&&t.condition(r)).sort((a,b)=>b.priority-a.priority||Number(b.decisive?.(r)??false)-Number(a.decisive?.(r)??false)||Number(!!b.characterId)-Number(!!a.characterId)||b.rarity-a.rarity||a.tieBreakOrder-b.tieBreakOrder)[0];
}
